export interface ThemeConfig {
  id: string;
  name: string;
  description: string;
  previewColor: string;
  // Classes and inline styling
  bgClass: string;
  navbarBg: string;
  footerBg: string;
  cardBg: string;
  primaryText: string;
  primaryBg: string;
  primaryHover: string;
  badgeBg: string;
  badgeText: string;
  borderClass: string;
  headingFont: string;
  bodyFont: string;
  shadowClass: string;
  gradientClass: string;
  glassClass?: string;
}

export const themes: Record<string, ThemeConfig> = {
  default: {
    id: 'default',
    name: 'Vibrant Orange (Default)',
    description: 'Bright culinary energy, modern fresh aesthetics, and appetizing orange highlights.',
    previewColor: 'from-orange-500 to-amber-400',
    bgClass: 'bg-slate-50/50',
    navbarBg: 'bg-white/95 backdrop-blur-md border-b border-slate-100',
    footerBg: 'bg-slate-900 border-t border-slate-800 text-slate-300',
    cardBg: 'bg-white border border-slate-100',
    primaryText: 'text-orange-500',
    primaryBg: 'bg-orange-500',
    primaryHover: 'hover:bg-orange-600',
    badgeBg: 'bg-orange-50 border-orange-100/50',
    badgeText: 'text-orange-600',
    borderClass: 'border-slate-100',
    headingFont: 'font-kuntomruy font-black',
    bodyFont: 'font-kuntomruy font-medium',
    shadowClass: 'shadow-md shadow-orange-500/5 hover:shadow-orange-500/10',
    gradientClass: 'from-primary to-orange-600',
  },
  minimal_dark_green: {
    id: 'minimal_dark_green',
    name: 'Sleek Dark Green – Grab',
    description: 'Sleek dark layout with Grab-inspired bright green accents, energetic and recognizable for ride & food delivery.',
    previewColor: 'from-slate-900 via-slate-800 to-green-500',
    bgClass: 'bg-slate-950 text-slate-100',
    navbarBg: 'bg-slate-900/90 backdrop-blur-md border-b border-slate-800/80',
    footerBg: 'bg-slate-950 border-t border-slate-800/50 text-slate-400',
    cardBg: 'bg-slate-900/70 border border-slate-800/60 backdrop-blur-xs',
    primaryText: 'text-green-400',
    primaryBg: 'bg-green-500',
    primaryHover: 'hover:bg-green-600',
    badgeBg: 'bg-green-950/50 border-green-900/40',
    badgeText: 'text-green-400',
    borderClass: 'border-slate-800/60',
    headingFont: 'font-kuntomruy font-black tracking-tight',
    bodyFont: 'font-kuntomruy font-medium text-slate-300',
    shadowClass: 'shadow-xl shadow-black/20 hover:shadow-green-500/5',
    gradientClass: 'from-green-500 to-lime-400',
  },
  elegant_rose: {
    id: 'elegant_rose',
    name: 'Luxury Gold & Rose',
    description: 'Royal aesthetics, delicate champagne accents, luxury gold borders, and elegant details.',
    previewColor: 'from-rose-500 to-amber-500',
    bgClass: 'bg-stone-50/60',
    navbarBg: 'bg-[#FAF6F0]/95 backdrop-blur-md border-b border-amber-500/10 text-slate-800',
    footerBg: 'bg-stone-950 border-t border-yellow-800/30 text-stone-300',
    cardBg: 'bg-white border border-stone-200/60',
    primaryText: 'text-rose-500',
    primaryBg: 'bg-rose-500',
    primaryHover: 'hover:bg-rose-600',
    badgeBg: 'bg-rose-50 border-rose-100',
    badgeText: 'text-rose-600',
    borderClass: 'border-stone-200/60',
    headingFont: 'font-kuntomruy font-black',
    bodyFont: 'font-kuntomruy font-semibold',
    shadowClass: 'shadow-md shadow-rose-900/5 hover:shadow-rose-900/10',
    gradientClass: 'from-rose-500 to-amber-500',
  },
  glass_gradient: {
    id: 'glass_gradient',
    name: 'Modern Glassmorphic',
    description: 'Frosted backdrops, vibrant cyan-purple mesh gradients, and floating futuristic controls.',
    previewColor: 'from-cyan-400 via-pink-500 to-purple-600',
    bgClass: 'bg-gradient-to-tr from-slate-900 via-purple-950 to-slate-900 text-slate-100 min-h-screen',
    navbarBg: 'bg-white/10 backdrop-blur-xl border-b border-white/10',
    footerBg: 'bg-black/40 backdrop-blur-xl border-t border-white/5 text-slate-400',
    cardBg: 'bg-white/5 backdrop-blur-xl border border-white/10 shadow-lg',
    primaryText: 'text-cyan-400',
    primaryBg: 'bg-gradient-to-r from-cyan-500 to-purple-500',
    primaryHover: 'hover:opacity-90',
    badgeBg: 'bg-cyan-500/10 border-cyan-400/20',
    badgeText: 'text-cyan-300',
    borderClass: 'border-white/10',
    headingFont: 'font-kuntomruy font-black',
    bodyFont: 'font-kuntomruy font-medium text-slate-200',
    shadowClass: 'shadow-2xl shadow-purple-950/20 hover:shadow-cyan-500/10',
    gradientClass: 'from-cyan-400 via-fuchsia-500 to-purple-600',
    glassClass: 'backdrop-blur-xl bg-white/5 border border-white/10 shadow-inner',
  },
  cafe_shop: {
    id: 'cafe_shop',
    name: 'Cafe & Coffee Shop',
    description: 'Warm coffee crema tints, rich hazelnut & wood highlights, Serifs headers, cozy cafe and coffee elements.',
    previewColor: 'from-amber-800 via-amber-700 to-yellow-600',
    bgClass: 'bg-[#FCF9F4] text-amber-950',
    navbarBg: 'bg-[#FCF9F4]/90 backdrop-blur-md border-b border-amber-900/10',
    footerBg: 'bg-[#1E1711] border-t border-amber-900/20 text-amber-200/70',
    cardBg: 'bg-white border border-amber-100/60 shadow-sm',
    primaryText: 'text-amber-700',
    primaryBg: 'bg-amber-700',
    primaryHover: 'hover:bg-amber-800',
    badgeBg: 'bg-amber-50 border-amber-200/50',
    badgeText: 'text-amber-800',
    borderClass: 'border-amber-100/60',
    headingFont: 'font-serif font-black',
    bodyFont: 'font-sans font-medium text-amber-900',
    shadowClass: 'shadow-md shadow-amber-950/5 hover:shadow-amber-950/10',
    gradientClass: 'from-amber-850 to-yellow-600',
  },
  electronic: {
    id: 'electronic',
    name: 'Electronic & Tech Store',
    description: 'Futuristic space-gray tech layout, glowing neon blue/cyan accents, glassmorphic badges.',
    previewColor: 'from-blue-600 via-indigo-900 to-cyan-500',
    bgClass: 'bg-[#0B0F19] text-slate-100 min-h-screen',
    navbarBg: 'bg-[#0E1322]/90 backdrop-blur-md border-b border-blue-950/40',
    footerBg: 'bg-[#06080F] border-t border-blue-950/40 text-slate-400',
    cardBg: 'bg-[#111827]/70 border border-blue-950/40 backdrop-blur-xs shadow-md',
    primaryText: 'text-cyan-400',
    primaryBg: 'bg-blue-600',
    primaryHover: 'hover:bg-blue-700',
    badgeBg: 'bg-blue-950/60 border-blue-800/40',
    badgeText: 'text-cyan-400',
    borderClass: 'border-blue-950/40',
    headingFont: 'font-sans font-black tracking-tight',
    bodyFont: 'font-sans font-medium text-slate-350',
    shadowClass: 'shadow-lg shadow-black/20 hover:shadow-cyan-500/5',
    gradientClass: 'from-blue-600 to-cyan-400',
    glassClass: 'backdrop-blur-xs bg-[#111827]/40 border border-blue-950/40 shadow-inner',
  },
  fashion: {
    id: 'fashion',
    name: 'Fashion & Style Boutique',
    description: 'Chic editorial minimal luxury, thin borders, elegant spacing, muted charcoal highlights.',
    previewColor: 'from-stone-900 via-stone-850 to-stone-500',
    bgClass: 'bg-[#F9F9F9] text-stone-900',
    navbarBg: 'bg-white border-b border-stone-200/60',
    footerBg: 'bg-[#151515] border-t border-stone-900 text-stone-400',
    cardBg: 'bg-white border border-stone-200/50 shadow-2xs',
    primaryText: 'text-stone-900',
    primaryBg: 'bg-stone-900',
    primaryHover: 'hover:bg-stone-850',
    badgeBg: 'bg-stone-100 border-stone-200',
    badgeText: 'text-stone-800',
    borderClass: 'border-stone-200/50',
    headingFont: 'font-serif font-black tracking-wide',
    bodyFont: 'font-sans font-semibold text-stone-600',
    shadowClass: 'shadow-3xs hover:shadow-2xs',
    gradientClass: 'from-stone-900 to-stone-550',
  },
  fashion_website_general: {
    id: 'fashion_website_general',
    name: 'Fashion General – Zine Style',
    description: 'Retro-themed zine style fashion catalog featuring blue badge stickers, high contrast product collages, and dynamic navigation.',
    previewColor: 'from-neutral-200 via-neutral-100 to-[#003CFF]',
    bgClass: 'bg-[#F9F9F9] text-stone-900',
    navbarBg: 'bg-white border-b border-stone-200/60',
    footerBg: 'bg-[#151515] border-t border-stone-900 text-stone-400',
    cardBg: 'bg-white border border-stone-200/50 shadow-2xs',
    primaryText: 'text-[#003CFF]',
    primaryBg: 'bg-stone-900',
    primaryHover: 'hover:bg-stone-850',
    badgeBg: 'bg-stone-100 border-stone-200',
    badgeText: 'text-stone-800',
    borderClass: 'border-stone-200/50',
    headingFont: 'font-serif font-black tracking-wide',
    bodyFont: 'font-sans font-semibold text-stone-600',
    shadowClass: 'shadow-3xs hover:shadow-2xs',
    gradientClass: 'from-[#003CFF] to-stone-550',
  },
  sweet_pastry: {
    id: 'sweet_pastry',
    name: 'Sweet Pastry & Bakery',
    description: 'Warm sugar pastel background, playful pink and bubblegum accents, cute dessert theme.',
    previewColor: 'from-pink-400 via-rose-350 to-violet-400',
    bgClass: 'bg-rose-50/30 text-rose-950',
    navbarBg: 'bg-[#FFF5F5]/95 backdrop-blur-md border-b border-pink-200/40',
    footerBg: 'bg-[#2D1B1B]/95 text-rose-250 border-t border-pink-900/10',
    cardBg: 'bg-white border border-pink-100/60 shadow-sm',
    primaryText: 'text-pink-500',
    primaryBg: 'bg-pink-500',
    primaryHover: 'hover:bg-pink-600',
    badgeBg: 'bg-pink-50 border-pink-100',
    badgeText: 'text-pink-600',
    borderClass: 'border-pink-100/60',
    headingFont: 'font-kuntomruy font-black',
    bodyFont: 'font-kuntomruy font-semibold text-rose-900',
    shadowClass: 'shadow-md shadow-pink-500/5 hover:shadow-pink-500/10',
    gradientClass: 'from-pink-500 to-rose-450',
  },
  minimal_dark_gold: {
    id: 'minimal_dark_gold',
    name: 'Luxury Obsidian & Gold',
    description: 'Deep obsidian backdrop, glowing liquid gold highlights, minimal luxury layout for upscale dining.',
    previewColor: 'from-black via-slate-900 to-yellow-600',
    bgClass: 'bg-[#09090b] text-[#fafafa] min-h-screen',
    navbarBg: 'bg-[#09090b]/90 backdrop-blur-md border-b border-amber-950/30',
    footerBg: 'bg-black border-t border-amber-950/30 text-[#eab308]/70',
    cardBg: 'bg-[#18181b]/70 border border-amber-950/30 backdrop-blur-xs shadow-md',
    primaryText: 'text-[#eab308]',
    primaryBg: 'bg-[#eab308]',
    primaryHover: 'hover:bg-[#ca8a04]',
    badgeBg: 'bg-[#451a03]/50 border-[#78350f]/30',
    badgeText: 'text-[#fef08a]',
    borderClass: 'border-amber-950/30',
    headingFont: 'font-serif font-black tracking-wide',
    bodyFont: 'font-sans font-medium text-stone-300',
    shadowClass: 'shadow-xl shadow-black/40 hover:shadow-yellow-500/5',
    gradientClass: 'from-yellow-600 to-amber-500',
    glassClass: 'backdrop-blur-xs bg-[#18181b]/40 border border-amber-950/30 shadow-inner',
  }
};
